kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "hello-node"
spec:
  source: 
    type: "Git"
    git:
      uri: "https://github.com/ivmfnal/kube"
      ref: "master"
    contextDir: "hello-node/docker"
